### ISSUE TITLE
Building on Raspberry Pi 4 w/ OpenGLES Support

### ISSUE THREAD

**Issue by 3-Hz** [bradleybauer/music_visualizer#8]
Do you have any plans to make this Raspberry Pi friendly? It would be super cool to deploy this on a Pi and have a portable low TDP audio visualizer that plugs into a projector or a TV.

**Comment by bradleybauer** [comment]
Sorry for not responding sooner but I have not done anything with this project for a long time.

Your suggestion is good. Although I do not have plans to add PI support. The primary focus of this project was to find interesting ways to process the audio stream so that it looks good when rendered at a common FPS (60hz/144hz). So I tend to do a lot of heavy computation / wasted computations while testing different audio processing functions. The current implementation of AudioProcessor is in a bit of an alpha/beta state and I cannot guarantee that it would be performant on a PI. But who knows, maybe it would run fine. Give it a shot.
